#!/usr/bin/env python3

from datetime import datetime
import json

# Update the JSON

with open('data.json', 'r', encoding='utf8') as data_file:
  data = json.load(data_file)
  
data['value'] += 1
data['updated'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

with open('data.json', 'w', encoding='utf8') as data_file:
  json.dump(data, data_file)
  
# Update the HTML

with open('index.html.template', 'r', encoding='utf8') as template_file:
  html_template = template_file.read()
    
html = html_template.replace('{{ value }}', data['value']).replace('{{ updated }}', data['updated'])

with open('docs/index.html', 'w', encoding='utf8') as html_file:
  html_file.write(html)
