#!/usr/bin/env python3

from datetime import datetime
import json

with open('data.json', 'r', encoding='utf8') as data_file:
  data = json.load(data_file)
  
data['value'] += 1
data['updated'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

with open('data.json', 'w', encoding='utf8') as data_file:
  json.dump(data, data_file)
