name: Update increment value

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '5,15,25,35,45,55 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Increment
      run: |-
        ./increment
    - name: Copy data file
      run: |-
        cp ./data.json ./docs/data.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest update: ${timestamp}" || exit 0
        git push
